<?php

class FilmsTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('films')->delete();
        
		\DB::table('films')->insert(array (
			0 => 
			array (
				'id' => 2,
				'categorie_film' => 3,
				'categorie_concours' => 1,
				'nom' => 'Adieu au langage',
				'duree' => 70,
				'nationalite' => 'FRANCE',
				'synopsis' => 'Le propos est simple, une femme mariée et un homme libre se rencontrent, ils s’aiment, se disputent, les coups pleuvent. Un chien erre entre ville et campagne, les saisons passent, l’homme et la femme se retrouvent. Le chien se trouve entre eux, l’autre est dans l’un, l’un est dans l’autre, Et ce sont les trois personnes. L’ancien mari fait tout exploser, Un deuxième film commence, Le même que le premier, Et pourtant pas, De l’espèce humaine on passe à la métaphore, ça finira par des aboiements, et des cris de bébé',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			1 => 
			array (
				'id' => 3,
				'categorie_film' => 4,
				'categorie_concours' => 1,
				'nom' => 'Captives',
				'duree' => 113,
				'nationalite' => 'CANADA',
				'synopsis' => '8 ans après la disparition de Cassandra, quelques indices troublants semblent indiquer qu\'elle est toujours vivante. La police, ses parents et Cassandra elle-même, vont essayer d élucider le mystère de sa disparition.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			2 => 
			array (
				'id' => 4,
				'categorie_film' => 6,
				'categorie_concours' => 1,
				'nom' => 'Deux jours, une nuit',
				'duree' => 95,
				'nationalite' => 'BELGIQUE FRANCE ITALIE',
				'synopsis' => 'Sandra, aidée par son mari, n\'a qu\'un week-end pour aller voir ses collègues et les convaincre de renoncer à leur prime pour qu\'elle puisse garder son travail.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			3 => 
			array (
				'id' => 5,
				'categorie_film' => 13,
				'categorie_concours' => 1,
				'nom' => 'Foxcatcher',
				'duree' => 134,
				'nationalite' => 'ETATS-UNIS',
				'synopsis' => 'Lorsque le médaillé d’or olympique Mark Schultz est invité par le riche héritier John du Pont à emménager dans sa magnifique propriété familiale pour aider à mettre en place un camp d’entraînement haut de gamme, dans l’optique des JO de Séoul de 1988, Schultz saute sur l’occasion.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			4 => 
			array (
				'id' => 6,
				'categorie_film' => 7,
				'categorie_concours' => 1,
				'nom' => 'Futatsume No Mado',
				'duree' => 118,
				'nationalite' => 'JAPON FRANCE ESPAGNE',
				'synopsis' => 'Sur l’île d’Amami, les habitants vivent en harmonie avec la nature, ils pensent qu’un dieu habite chaque arbre, chaque pierre et chaque plante. Un soir d\'été, Kaito découvre le corps d’un homme flottant dans la mer, sa jeune amie Kyoko va l’aider à percer ce mystère. Ensemble, ils apprennent à devenir adultes et découvrent les cycles de la vie, de la mort et de l’amour.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			5 => 
			array (
				'id' => 7,
				'categorie_film' => 8,
				'categorie_concours' => 1,
				'nom' => 'Jimmy’s Hall',
				'duree' => 108,
				'nationalite' => 'ROYAUME-UNI FRANCE IRLANDE',
				'synopsis' => '1932 - Après un exil de dix ans aux États-Unis, Jimmy Gralton rentre au pays pour aider sa mère à s\'occuper de la ferme familiale.L\'Irlande qu\'il retrouve, une dizaine d\'années après la guerre civile, s\'est dotée d\'un nouveau gouvernement. Tous les espoirs sont permis.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			6 => 
			array (
				'id' => 8,
				'categorie_film' => 12,
				'categorie_concours' => 1,
				'nom' => 'Le Meraviglie',
				'duree' => 110,
				'nationalite' => 'SUISSE ITALIE ALLEMAGNE',
				'synopsis' => 'Dans un village en Ombrie, c\'est la fin de l\'été. Gelsomina vit avec ses parents et ses trois jeunes sœurs, dans une ferme délabrée où ils produisent du miel. Volontairement tenues à distance du monde par leur père, qui en prédit la fin proche et prône un rapport privilégié à la nature, les filles grandissent en marge.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			7 => 
			array (
				'id' => 9,
				'categorie_film' => 11,
				'categorie_concours' => 1,
				'nom' => 'Leviathan',
				'duree' => 141,
				'nationalite' => 'RUSSIE',
				'synopsis' => 'Kolia habite une petite ville au bord de la mer de Barents, au nord de la Russie. Il tient un garage qui jouxte la maison où il vit avec sa jeune femme Lylia et son fils Romka qu’il a eu d’un précédent mariage. Vadim Sergeyich, le Maire de la ville, souhaite s’approprier le terrain de Kolia, sa maison et son garage. Il a des projets. Il tente d’abord de l’acheter mais Kolia ne peut pas supporter l’idée de perdre tout ce qu’il possède.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			8 => 
			array (
				'id' => 10,
				'categorie_film' => 1,
				'categorie_concours' => 1,
				'nom' => 'Maps to the stars',
				'duree' => 141,
				'nationalite' => 'CANADA ALLEMAGNE',
				'synopsis' => 'À Hollywood, la ville des rêves, se télescopent les étoiles : Benjie, 13 ans et déjà star; son père, Sanford Weiss, auteur à succès et coach des célébrités; sa cliente, la belle Havana Segrand, qu’il aide à se réaliser en tant que femme et actrice.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			9 => 
			array (
				'id' => 11,
				'categorie_film' => 13,
				'categorie_concours' => 1,
				'nom' => 'Foxcatcher',
				'duree' => 134,
				'nationalite' => 'ETATS-UNIS',
				'synopsis' => 'Lorsque le médaillé d’or olympique Mark Schultz est invité par le riche héritier John du Pont à emménager dans sa magnifique propriété familiale pour aider à mettre en place un camp d’entraînement haut de gamme, dans l’optique des JO de Séoul de 1988, Schultz saute sur l’occasion.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			10 => 
			array (
				'id' => 12,
				'categorie_film' => 7,
				'categorie_concours' => 1,
				'nom' => 'Futatsume No Mado',
				'duree' => 118,
				'nationalite' => 'JAPON FRANCE ESPAGNE',
				'synopsis' => 'Sur l’île d’Amami, les habitants vivent en harmonie avec la nature, ils pensent qu’un dieu habite chaque arbre, chaque pierre et chaque plante. Un soir d\'été, Kaito découvre le corps d’un homme flottant dans la mer, sa jeune amie Kyoko va l’aider à percer ce mystère. Ensemble, ils apprennent à devenir adultes et découvrent les cycles de la vie, de la mort et de l’amour.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			11 => 
			array (
				'id' => 13,
				'categorie_film' => 8,
				'categorie_concours' => 1,
				'nom' => 'Jimmy’s Hall',
				'duree' => 108,
				'nationalite' => 'ROYAUME-UNI FRANCE IRLANDE',
				'synopsis' => '1932 - Après un exil de dix ans aux États-Unis, Jimmy Gralton rentre au pays pour aider sa mère à s\'occuper de la ferme familiale.L\'Irlande qu\'il retrouve, une dizaine d\'années après la guerre civile, s\'est dotée d\'un nouveau gouvernement. Tous les espoirs sont permis.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			12 => 
			array (
				'id' => 14,
				'categorie_film' => 12,
				'categorie_concours' => 1,
				'nom' => 'Le Meraviglie',
				'duree' => 110,
				'nationalite' => 'SUISSE ITALIE ALLEMAGNE',
				'synopsis' => 'Dans un village en Ombrie, c\'est la fin de l\'été. Gelsomina vit avec ses parents et ses trois jeunes sœurs, dans une ferme délabrée où ils produisent du miel. Volontairement tenues à distance du monde par leur père, qui en prédit la fin proche et prône un rapport privilégié à la nature, les filles grandissent en marge.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			13 => 
			array (
				'id' => 15,
				'categorie_film' => 11,
				'categorie_concours' => 1,
				'nom' => 'Leviathan',
				'duree' => 141,
				'nationalite' => 'RUSSIE',
				'synopsis' => 'Kolia habite une petite ville au bord de la mer de Barents, au nord de la Russie. Il tient un garage qui jouxte la maison où il vit avec sa jeune femme Lylia et son fils Romka qu’il a eu d’un précédent mariage. Vadim Sergeyich, le Maire de la ville, souhaite s’approprier le terrain de Kolia, sa maison et son garage. Il a des projets. Il tente d’abord de l’acheter mais Kolia ne peut pas supporter l’idée de perdre tout ce qu’il possède.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			14 => 
			array (
				'id' => 16,
				'categorie_film' => 1,
				'categorie_concours' => 1,
				'nom' => 'Maps to the stars',
				'duree' => 141,
				'nationalite' => 'CANADA ALLEMAGNE',
				'synopsis' => 'À Hollywood, la ville des rêves, se télescopent les étoiles : Benjie, 13 ans et déjà star; son père, Sanford Weiss, auteur à succès et coach des célébrités; sa cliente, la belle Havana Segrand, qu’il aide à se réaliser en tant que femme et actrice. ',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			15 => 
			array (
				'id' => 17,
				'categorie_film' => 3,
				'categorie_concours' => 2,
				'nom' => 'Amour Fou',
				'duree' => 96,
				'nationalite' => 'AUTRICHE',
				'synopsis' => 'En transit dans un hôtel international près de Roissy, un ingénieur en informatique américain, soumis à de très lourdes pressions professionnelles et affectives, décide de changer radicalement le cours de sa vie. Quelques heures plus tard, une jeune femme de chambre de l’hôtel, qui vit dans un entre-deux provisoire, voit son existence basculer à la suite d’un événement surnaturel.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			16 => 
			array (
				'id' => 18,
				'categorie_film' => 4,
				'categorie_concours' => 2,
				'nom' => 'Bird People',
				'duree' => 128,
				'nationalite' => 'FRANCE',
				'synopsis' => 'Berlin, à l’époque romantique. Le jeune poète tragique Heinrich souhaite dépasser le côté inéluctable de la mort grâce à l’amour: il tente de convaincre sa cousine Marie, qui lui est proche, de contrer le destin en déterminant ensemble leur suicide, mais Marie reste sceptique malgré son insistance.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			17 => 
			array (
				'id' => 19,
				'categorie_film' => 5,
				'categorie_concours' => 2,
				'nom' => 'Charlie’s Country',
				'duree' => 108,
				'nationalite' => 'AUSTRALIE',
				'synopsis' => 'Blackfella Charlie n’est pas content. L’intervention du gouvernement rend la vie plus difficile dans sa communauté isolée où les lois des blancs sont maintenant appliquées plus strictement. Charlie décide alors de prendre la route pour suivre l’ancien mode de vie, mais ce faisant il déclenche une suite d’événements qui aboutira à son retour dans sa communauté, assagi et un peu plus raisonnable',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			18 => 
			array (
				'id' => 20,
				'categorie_film' => 6,
				'categorie_concours' => 2,
				'nom' => 'Dohee-Ya',
				'duree' => 119,
				'nationalite' => 'CORÉE',
				'synopsis' => 'Suite à un incident, Young-nam, jeune policière de Séoul, est transférée dans un petit village côtier. Dès son arrivée, elle croise Dohee, une adolescente dont l’allure renfermée l’intrigue. Dans ce nouvel environnement, Young-nam fait la connaissance du beau-père de Dohee, un homme violent et alcoolique exploitant des travailleurs immigrés. Pour protéger Dohee des mauvais traitements de son beau-père, Young-nam l’héberge chez elle. La jeune femme découvre alors les différentes facettes de la personnalité de Dohee',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			19 => 
			array (
				'id' => 21,
				'categorie_film' => 9,
				'categorie_concours' => 2,
				'nom' => 'Fantasia',
				'duree' => 85,
				'nationalite' => 'CHINE',
				'synopsis' => 'Père a la leucémie.Mère est au chômage depuis long temps.Elle emprunte de l\'argent pour son mari partout.Grande sœur va travailler secrètement dans une boîte de nuit comme serveuse,et très vite devient prostituée.Lin est aliéné à l\'école à cause de la maladie de son père.Il est dégoûté.Un jour,au bord de la rivière,il trouve un navire délabré et fait connaissance d’un père et d’une fille étrange.Lin devient ami avec la fille,et leur aide à voler des pierres de fer.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			20 => 
			array (
				'id' => 22,
				'categorie_film' => 8,
				'categorie_concours' => 2,
				'nom' => 'Féher Isten',
				'duree' => 119,
				'nationalite' => 'HONGRIE SUEDE ALLEMAGNE',
				'synopsis' => 'Un conte visionnaire entre une espèce supérieure et ses congénères en disgrâce… Privilégiant les chiens de race, une nouvelle loi impose une lourde taxe sur les races croisées. Les refuges sont vite bondés par des bâtards abandonnés. Lili, 13 ans, se bat pour protéger son chien, Hagen, mais son père le relâche dans les rues.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			21 => 
			array (
				'id' => 23,
				'categorie_film' => 9,
				'categorie_concours' => 2,
				'nom' => 'Hersoma Juventud',
				'duree' => 103,
				'nationalite' => 'FRANCE ESPAGNE',
				'synopsis' => 'Natalia et Carlos sont deux jeunes amoureux de 20 ans qui se battent pour survivre dans l’Espagne actuelle. Leurs ressources limitées les empêchent d’évoluer comme ils le souhaiteraient. Ils n’ont pas de grandes ambitions parce qu’ils n’abritent pas de grandes espérances. Pour gagner un peu d’argent, ils décident de tourner un film porno amateur. La naissance de leur fille, Julia, sera le principal moteur de leurs changements.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			22 => 
			array (
				'id' => 24,
				'categorie_film' => 10,
				'categorie_concours' => 2,
				'nom' => 'Jauja',
				'duree' => 108,
				'nationalite' => 'ARGENTINE PAYS-BAS MEXIQUE',
				'synopsis' => 'Les Anciens disaient que Jauja était, dans la mythologie, une terre d\'abondance et de bonheur. Beaucoup d\'expéditions ont cherché ce lieu pour en avoir la preuve. Avec le temps, la légende s’est amplifiée d\'une manière disproportionnée. Sans doute les gens exagéraient-ils, comme d’habitude. La seule chose que l\'on sait avec certitude, c\'est que tous ceux qui ont essayé de trouver ce paradis terrestre se sont perdus en chemin.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			23 => 
			array (
				'id' => 25,
				'categorie_film' => 10,
				'categorie_concours' => 2,
				'nom' => 'La chambre bleue',
				'duree' => 76,
				'nationalite' => 'FRANCE',
				'synopsis' => 'Un homme et une femme s’aiment en secret dans une chambre, se désirent, se veulent, se mordent même. Puis s’échangent quelques mots anodins après l’amour. Du moins l’homme semble le croire.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			24 => 
			array (
				'id' => 26,
				'categorie_film' => 11,
				'categorie_concours' => 2,
				'nom' => 'Loin de mon père',
				'duree' => 94,
				'nationalite' => 'ISRAEL',
				'synopsis' => 'Moshe et Tami sont en couple. Moshe a cinquante ans, Tami est à peine entrée dans la vingtaine. Ils vivent une relation cruelle et violente dont Tami ne semble pas pouvoir se libérer. Tami et Moshe sont père et fille',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			25 => 
			array (
				'id' => 27,
				'categorie_film' => 13,
				'categorie_concours' => 2,
				'nom' => 'Lost River',
				'duree' => 105,
				'nationalite' => 'ETATS-UNIS',
				'synopsis' => 'Dans une ville qui se meurt, Billy, mère célibataire de deux enfants, est entraînée peu à peu dans les bas-fonds d’un monde sombre et macabre, pendant que Bones, son fils aîné, découvre une route secrète menant à une ville engloutie. Billy et son fils devront affronter bien des obstacles pour que leur famille s’en sorte.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			26 => 
			array (
				'id' => 28,
				'categorie_film' => 2,
				'categorie_concours' => 2,
				'nom' => 'Party girl',
				'duree' => 96,
				'nationalite' => 'FRANCE',
				'synopsis' => 'Angélique a soixante ans. Elle aime encore la fête, elle aime encore les hommes. La nuit, pour gagner sa vie, elle les fait boire dans un cabaret à la frontière allemande. Avec le temps, les clients se font plus rares. Mais Michel, son habitué, est toujours amoureux d’elle. Un jour, il lui propose de l’épouser.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			27 => 
			array (
				'id' => 29,
				'categorie_film' => 2,
				'categorie_concours' => 2,
				'nom' => 'Run',
				'duree' => 100,
				'nationalite' => 'FRANCE COTE D\'IVOIRE',
				'synopsis' => 'Run s’enfuit… Il vient de tuer le Premier ministre de son pays. Pour cela il a dû prendre le visage et les vêtements d’un fou, errant à travers la ville. Sa vie lui revient par flashes ; son enfance avec maître Tourou quand il rêvait de devenir faiseur de pluie, ses aventures avec Gladys la mangeuse et son passé de milicien en tant que Jeune Patriote, au coeur du conflit politique et militaire en Côte d’Ivoire. Toutes ses vies, Run ne les a pas choisies.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			28 => 
			array (
				'id' => 30,
				'categorie_film' => 1,
				'categorie_concours' => 2,
				'nom' => 'Snow Paradise',
				'duree' => 108,
				'nationalite' => 'ROYAUME-UNI',
				'synopsis' => 'Dave est un petit délinquant qui mène sa vie, entre drogue et violence, dans l\'East End de Londres. Quand son « business » entraîne la mort de Tariq, son meilleur ami, Dave est terrassé, pour la première fois de sa vie, par la honte et le remords. Alors qu\'il commence à faire la paix avec lui-même, son passé de criminel revient le mettre à l\'épreuve.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			29 => 
			array (
				'id' => 31,
				'categorie_film' => 3,
				'categorie_concours' => 2,
				'nom' => 'Amour Fou',
				'duree' => 96,
				'nationalite' => 'AUTRICHE',
				'synopsis' => 'En transit dans un hôtel international près de Roissy, un ingénieur en informatique américain, soumis à de très lourdes pressions professionnelles et affectives, décide de changer radicalement le cours de sa vie. Quelques heures plus tard, une jeune femme de chambre de l’hôtel, qui vit dans un entre-deux provisoire, voit son existence basculer à la suite d’un événement surnaturel.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			30 => 
			array (
				'id' => 32,
				'categorie_film' => 4,
				'categorie_concours' => 2,
				'nom' => 'Bird People',
				'duree' => 128,
				'nationalite' => 'FRANCE',
				'synopsis' => 'Berlin, à l’époque romantique. Le jeune poète tragique Heinrich souhaite dépasser le côté inéluctable de la mort grâce à l’amour: il tente de convaincre sa cousine Marie, qui lui est proche, de contrer le destin en déterminant ensemble leur suicide, mais Marie reste sceptique malgré son insistance.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			31 => 
			array (
				'id' => 33,
				'categorie_film' => 5,
				'categorie_concours' => 2,
				'nom' => 'Charlie’s Country',
				'duree' => 108,
				'nationalite' => 'AUSTRALIE',
				'synopsis' => 'Blackfella Charlie n’est pas content. L’intervention du gouvernement rend la vie plus difficile dans sa communauté isolée où les lois des blancs sont maintenant appliquées plus strictement. Charlie décide alors de prendre la route pour suivre l’ancien mode de vie, mais ce faisant il déclenche une suite d’événements qui aboutira à son retour dans sa communauté, assagi et un peu plus raisonnable',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			32 => 
			array (
				'id' => 34,
				'categorie_film' => 6,
				'categorie_concours' => 2,
				'nom' => 'Dohee-Ya',
				'duree' => 119,
				'nationalite' => 'CORÉE',
				'synopsis' => 'Suite à un incident, Young-nam, jeune policière de Séoul, est transférée dans un petit village côtier. Dès son arrivée, elle croise Dohee, une adolescente dont l’allure renfermée l’intrigue. Dans ce nouvel environnement, Young-nam fait la connaissance du beau-père de Dohee, un homme violent et alcoolique exploitant des travailleurs immigrés. Pour protéger Dohee des mauvais traitements de son beau-père, Young-nam l’héberge chez elle. La jeune femme découvre alors les différentes facettes de la personnalité de Dohee',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			33 => 
			array (
				'id' => 35,
				'categorie_film' => 9,
				'categorie_concours' => 2,
				'nom' => 'Fantasia',
				'duree' => 85,
				'nationalite' => 'CHINE',
				'synopsis' => 'Père a la leucémie.Mère est au chômage depuis long temps.Elle emprunte de l\'argent pour son mari partout.Grande sœur va travailler secrètement dans une boîte de nuit comme serveuse,et très vite devient prostituée.Lin est aliéné à l\'école à cause de la maladie de son père.Il est dégoûté.Un jour,au bord de la rivière,il trouve un navire délabré et fait connaissance d’un père et d’une fille étrange.Lin devient ami avec la fille,et leur aide à voler des pierres de fer.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			34 => 
			array (
				'id' => 36,
				'categorie_film' => 8,
				'categorie_concours' => 2,
				'nom' => 'Féher Isten',
				'duree' => 119,
				'nationalite' => 'HONGRIE SUEDE ALLEMAGNE',
				'synopsis' => 'Un conte visionnaire entre une espèce supérieure et ses congénères en disgrâce… Privilégiant les chiens de race, une nouvelle loi impose une lourde taxe sur les races croisées. Les refuges sont vite bondés par des bâtards abandonnés. Lili, 13 ans, se bat pour protéger son chien, Hagen, mais son père le relâche dans les rues.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			35 => 
			array (
				'id' => 37,
				'categorie_film' => 9,
				'categorie_concours' => 2,
				'nom' => 'Hersoma Juventud',
				'duree' => 103,
				'nationalite' => 'FRANCE ESPAGNE',
				'synopsis' => 'Natalia et Carlos sont deux jeunes amoureux de 20 ans qui se battent pour survivre dans l’Espagne actuelle. Leurs ressources limitées les empêchent d’évoluer comme ils le souhaiteraient. Ils n’ont pas de grandes ambitions parce qu’ils n’abritent pas de grandes espérances. Pour gagner un peu d’argent, ils décident de tourner un film porno amateur. La naissance de leur fille, Julia, sera le principal moteur de leurs changements.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			36 => 
			array (
				'id' => 38,
				'categorie_film' => 10,
				'categorie_concours' => 2,
				'nom' => 'Jauja',
				'duree' => 108,
				'nationalite' => 'ARGENTINE PAYS-BAS MEXIQUE',
				'synopsis' => 'Les Anciens disaient que Jauja était, dans la mythologie, une terre d\'abondance et de bonheur. Beaucoup d\'expéditions ont cherché ce lieu pour en avoir la preuve. Avec le temps, la légende s’est amplifiée d\'une manière disproportionnée. Sans doute les gens exagéraient-ils, comme d’habitude. La seule chose que l\'on sait avec certitude, c\'est que tous ceux qui ont essayé de trouver ce paradis terrestre se sont perdus en chemin.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			37 => 
			array (
				'id' => 39,
				'categorie_film' => 10,
				'categorie_concours' => 2,
				'nom' => 'La chambre bleue',
				'duree' => 76,
				'nationalite' => 'FRANCE',
				'synopsis' => 'Un homme et une femme s’aiment en secret dans une chambre, se désirent, se veulent, se mordent même. Puis s’échangent quelques mots anodins après l’amour. Du moins l’homme semble le croire.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			38 => 
			array (
				'id' => 40,
				'categorie_film' => 11,
				'categorie_concours' => 2,
				'nom' => 'Loin de mon père',
				'duree' => 94,
				'nationalite' => 'ISRAEL',
				'synopsis' => 'Moshe et Tami sont en couple. Moshe a cinquante ans, Tami est à peine entrée dans la vingtaine. Ils vivent une relation cruelle et violente dont Tami ne semble pas pouvoir se libérer. Tami et Moshe sont père et fille',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			39 => 
			array (
				'id' => 41,
				'categorie_film' => 13,
				'categorie_concours' => 2,
				'nom' => 'Lost River',
				'duree' => 105,
				'nationalite' => 'ETATS-UNIS',
				'synopsis' => 'Dans une ville qui se meurt, Billy, mère célibataire de deux enfants, est entraînée peu à peu dans les bas-fonds d’un monde sombre et macabre, pendant que Bones, son fils aîné, découvre une route secrète menant à une ville engloutie. Billy et son fils devront affronter bien des obstacles pour que leur famille s’en sorte.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			40 => 
			array (
				'id' => 42,
				'categorie_film' => 2,
				'categorie_concours' => 2,
				'nom' => 'Party girl',
				'duree' => 96,
				'nationalite' => 'FRANCE',
				'synopsis' => 'Angélique a soixante ans. Elle aime encore la fête, elle aime encore les hommes. La nuit, pour gagner sa vie, elle les fait boire dans un cabaret à la frontière allemande. Avec le temps, les clients se font plus rares. Mais Michel, son habitué, est toujours amoureux d’elle. Un jour, il lui propose de l’épouser.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			41 => 
			array (
				'id' => 43,
				'categorie_film' => 2,
				'categorie_concours' => 2,
				'nom' => 'Run',
				'duree' => 100,
				'nationalite' => 'FRANCE COTE D\'IVOIRE',
				'synopsis' => 'Run s’enfuit… Il vient de tuer le Premier ministre de son pays. Pour cela il a dû prendre le visage et les vêtements d’un fou, errant à travers la ville. Sa vie lui revient par flashes ; son enfance avec maître Tourou quand il rêvait de devenir faiseur de pluie, ses aventures avec Gladys la mangeuse et son passé de milicien en tant que Jeune Patriote, au coeur du conflit politique et militaire en Côte d’Ivoire. Toutes ses vies, Run ne les a pas choisies.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			42 => 
			array (
				'id' => 44,
				'categorie_film' => 1,
				'categorie_concours' => 2,
				'nom' => 'Snow Paradise',
				'duree' => 108,
				'nationalite' => 'ROYAUME-UNI',
				'synopsis' => 'Dave est un petit délinquant qui mène sa vie, entre drogue et violence, dans l\'East End de Londres. Quand son « business » entraîne la mort de Tariq, son meilleur ami, Dave est terrassé, pour la première fois de sa vie, par la honte et le remords. Alors qu\'il commence à faire la paix avec lui-même, son passé de criminel revient le mettre à l\'épreuve.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			43 => 
			array (
				'id' => 45,
				'categorie_film' => 4,
				'categorie_concours' => 2,
				'nom' => 'The disappearence of Eleanor Rigby',
				'duree' => 119,
				'nationalite' => 'ETATS-UNIS',
				'synopsis' => 'James McAvoy et Jessica Chastain sont un couple admiré de tous, en apparence très amoureux, jusqu\'au jour où leur mariage est complètement ébranlé par le coup du destin. Ce couple new yorkais doit aujourd\'hui essayer de se comprendre tout en faisant leur deuil et en essayant de ressusciter leur amour et retrouver leur vie d\'avant.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			44 => 
			array (
				'id' => 46,
				'categorie_film' => 9,
				'categorie_concours' => 2,
				'nom' => 'The salt of the earth',
				'duree' => 109,
				'nationalite' => 'FRANCE',
				'synopsis' => 'Depuis quarante ans, le photographe Sebastião Salgado parcourt les continents sur les traces d’une humanité en pleine mutation. Alors qu’il a témoigné des événements majeurs qui ont marqué notre histoire récente : conflits internationaux, famine, exode…, il se lance à présent à la découverte de territoires vierges aux paysages grandioses, à la rencontre d’une faune et d’une flore sauvages dans un gigantesque projet photographique, hommage à la beauté de la planète.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			45 => 
			array (
				'id' => 47,
				'categorie_film' => 3,
				'categorie_concours' => 2,
				'nom' => 'Titli',
				'duree' => 124,
				'nationalite' => 'INDE',
				'synopsis' => 'ans les quartiers mal-fâmés de la banlieue de Delhi, Titli, benjamin d\'une fratrie de violents braqueurs de voitures, tente désespérément d\'échapper à l\'entreprise familiale.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			46 => 
			array (
				'id' => 48,
				'categorie_film' => 6,
				'categorie_concours' => 2,
				'nom' => 'Turist',
				'duree' => 118,
				'nationalite' => 'SUEDE',
				'synopsis' => 'Une famille suédoise passe ses vacances d\'hiver dans les Alpes. Le soleil brille et les pistes sont magnifiques mais lors d’un déjeuner dans un restaurant de montagne, une avalanche vient tout bouleverser. Les clients du restaurant sont pris de panique, Ebba, la mère, appelle son mari Tomas à l’aide tout en essayant de protéger leurs enfants, alors que Tomas, lui, a pris la fuite ne pensant qu’à sauver sa vie.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
			47 => 
			array (
				'id' => 49,
				'categorie_film' => 8,
				'categorie_concours' => 2,
				'nom' => 'Xenia',
				'duree' => 128,
				'nationalite' => 'FRANCE GRECE BELGIQUE',
				'synopsis' => 'A la mort de leur mère, Dany et son frère Odysseas, 16 et 18 ans, prennent la route d’Athènes à Thessalonique pour retrouver leur père, un Grec qu’ils n’ont jamais connu. Albanais par leur mère, ils sont étrangers dans leur propre pays et veulent que ce père les reconnaisse pour obtenir la nationalité grecque. Dany et Ody se sont aussi promis de participer à un populaire concours de chant qui pourrait rendre leur vie meilleure.',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),
		));
	}

}
